#!/bin/bash

curl -w foo http://localhost:8080/ &
curl -w bar http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &
curl -w baz http://localhost:8080/ &

wait
